### ISSUE TITLE
Need to include the description of the app.

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/notepad#1]
As of now, there is no description in the webpage on what the app does. So a landing page is needed. 
This is an app where one can write anywhere on the screen.

**Comment by Muskan284** [comment]
Hey, can I grab this one?

**Comment by agnelvishal** [comment]
> Hey, can I grab this one?

First you may want to try the simple app from https://sarchy.co/notepad
Then you can create a landing page about it
